/**
 * Jenkins pipeline building patched EC and SunP11 JARs.
 *
 */
pipeline {
    agent {
        dockerfile {
            label 'dss-docker'
            dir "jenkins-files/containers/${env.CONTAINER}"
            filename 'Dockerfile'
            additionalBuildArgs  '--disable-content-trust=false --pull -m 512m --memory-swap 512m'
            args '--user user --group-add root -m 2g --memory-swap 2g'
        }
    }

    stages {
        stage('Verify Environment') {
            steps {
                // Print versions
                sh "java -version"
                sh "locale"
                sh "echo Workspace: ${WORKSPACE}"
                sh "printenv"
                sh "ls -l"
            }
        }
        stage('Package') {
            steps {
                archiveArtifacts '*.jar'
            }
        }
    }
}
