pipeline {
	agent {
		label "dss-docker"
	}
// NB: this is not a jenkins SVN pipeline script, but a normal one - because we don't want 
// pipeline to check in code for this job, we only want to  perform a quick prune.
    stages {
        stage('Docker info before  system prune') {
            steps {
                echo "************All Containers and its size before system prune****************"
                sh "docker container ls -as"
                echo "************************All Images before system prune*********************"
                sh "docker image ls -a --no-trunc"
                echo "************************All volumes before system prune*********************"
                sh "docker volume ls"
                echo "************************All Networks before system prune*********************"
                sh "docker network ls"
                echo "************************Docker info before system prune*********************"
                sh "docker info"
                echo "**********************system space before system prune**********************"
                sh "df -h"
            }
        }
        stage('Docker info after system prune') {
            steps {
                echo "*******************system prune*******************************************"
                sh "docker system prune -f -a --volumes"
                echo "************All Containers and its size after system prune****************"
                sh "docker container ls -as"
                echo "************************All Images info after system prune*********************"
                sh "docker image ls -a --no-trunc"
                echo "************************All volumes details after system prune*********************"
                sh "docker volume ls"
                echo "************************All Networks details after system prune*********************"
                sh "docker network ls"
                echo "************************Docker info after system prune*********************"
                sh "docker info"
                echo "**********************system space after system prune**********************"
                sh "df -h"
            }
        }
    }
}
