pipeline {
	agent {
                dockerfile {
                    label 'dss-docker'
                    dir "jenkins-files/containers/${env.CONTAINER}"
                    filename 'Dockerfile'
                    additionalBuildArgs  '--disable-content-trust=false --pull'
                    args '--group-add root --volume m2-repo:/m2-repo'
                }
	}
    
    stages {
        stage('Verify Environment') {
            steps {
                // Print versions
                sh "java -version"
                sh "mvn -version"
                sh "ant -version"
                sh "locale"
                def workspace = pwd()
                sh "echo workspace: ${workspace}"

                // Init edition
                dir ('signserver') {
                    sh "ant -q init"

                    // Check expected edition
                    // TODO
                }
            }
        }
        stage('Build') {
            steps {
                def workspace = pwd()
                dir ('signserver') {
                    sh "mvn -Dmaven.repo.local=${workspace}/m2-repo clean install -DskipTests"
                }
            }
        }
        stage('Unit Test') {
            steps {
                def workspace = pwd()
                dir ('signserver') {
                    withEnv(['SIGNSERVER_NODEID=node1.example.com']) {                     
                        sh "mvn -Dmaven.repo.local=${workspace}/m2-repo test"

                        // gather the results
                        junit "**/target/surefire-reports/*.xml"
                    }
                }
            }
        }
        stage('Package') {
            steps {
                dir ('signserver') {
                    // Create the release
                    sh "ant release:binary-zip"
                }
                archiveArtifacts 'signserver-*-bin.zip'
            }
        }
        stage('Javadoc') {
            steps {
                def workspace = pwd()
                dir ('signserver') {
                    // Build Javadoc
                    sh "mvn -Dmaven.repo.local=${workspace}/m2-repo javadoc:aggregate"
                }
            }
        }

    }
    post {
        always {
            cleanWs()
        }
    }
}
