pipeline {
	agent {
                dockerfile {
                    label 'dss-docker'
                    dir 'jenkins-files/test-markus-docker'
                    filename 'Dockerfile'
                    additionalBuildArgs  '--disable-content-trust=false --pull'
                    args '--group-add root'
                }
	}
    
    stages {
        stage('Verify Environment') {
            steps {
                // Print versions
                sh "java -version"
                sh "mvn -version"
                sh "ant -version"

                // Init edition
                dir ('signserver') {
                    sh "ant -q init"

                    // Check expected edition
                    // TODO
                }
            }
        }
        stage('Build') {
            steps {
                dir ('signserver') {
                    sh "mvn clean install -DskipTests"
                }
            }
        }
        stage('Unit Test') {
            steps {
                dir ('signserver') {
                    withEnv(['SIGNSERVER_NODEID=node1.example.com']) {                     
                        sh "mvn test"

                        // gather the results
                        junit "**/target/surefire-reports/*.xml"
                    }
                }
            }
        }
        stage('Package') {
            steps {
                dir ('signserver') {
                    // Create the release
                    sh "ant release:binary-zip"
                }
                archiveArtifacts 'signserver-*-bin.zip'
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
